### ISSUE TITLE
Code invalid

### ISSUE THREAD

**Issue by yixiyixi5** [WONQIAN/texture-analysis#1]
请问这篇论文“TEXEMS: Texture exemplars for defect detection on random textured surfaces”的代码链接失效了，有其他的可用链接吗？谢谢

**Comment by smiler96** [comment]
这个作者没有提供源码，不过你可以去他官网看下，这篇文章很经典

**Comment by yixiyixi5** [comment]
好的，谢谢


 
---Original---
